name: CI

on: [push, pull_request]

jobs:
  job_build:
    name: Compilation for NanoS

    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "$NANOS_SDK"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=0 COIN=groestlcoin BOLOS_SDK=${{ matrix.SDK }} && mv bin/ groestlcoin-bin/
          make clean
          make DEBUG=0 COIN=groestlcoin_testnet BOLOS_SDK=${{ matrix.SDK }} && mv bin/ groestlcoin-testnet-bin/

      - name: Upload Groestlcoin app binary
        uses: actions/upload-artifact@v2
        with:
          name: groestlcoin-app-${{ matrix.model }}
          path: groestlcoin-bin

      - name: Upload Groestlcoin Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: groestlcoin-testnet-app-${{ matrix.model }}
          path: groestlcoin-testnet-bin
